
Citizen.CreateThread(function()
	AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	--AddTextEntry("tesla895", "Tesla Model S")
	end)

	print("^4Zeluck#9999 ^7| ^1Name véhicule démarré !")
-- Dev  by Zeluck#9999
