
Citizen.CreateThread(function()
	AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	--AddTextEntry("rs6", "Audi RS6")
	end)

	print("^4Zeluck#9999 ^7| ^1Name véhicule démarré !")
-- Dev  by Zeluck#9999